# Comment to be posted to on first time issues
newIssueWelcomeComment: |
  Thanks for opening your first issue! 
  Kindly note that this repository is maintained by [Vinit Shahdeo](https://www.linkedin.com/in/vinitshahdeo/). 
  He'll get back to you soon. Meanwhile check [this](https://github.com/vinitshahdeo/Hacktoberfest2021/) repo for more.
 
# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
 Thanks for opening this pull request! 🤗
 Wishing you a great [Hacktoberfest 2022](https://vinitshahdeo.dev/hacktoberfest-2021) 🙌 🎉 ⚡️
 **Are you looking for more beginner-friendly issues? Check out [this](https://github.com/vinitshahdeo/Hacktoberfest2021) repo.**
 
 [![Open Source Love](https://badges.frapsoft.com/os/v2/open-source.svg?v=103)](https://github.com/vinitshahdeo)
 
 **Check out few other repos below** 🚀
 
 [![PortScanner](https://github-readme-stats.vercel.app/api/pin/?username=vinitshahdeo&repo=PortScanner)](https://github.com/vinitshahdeo/PortScanner) 
 [![SimpleBio](https://github-readme-stats.vercel.app/api/pin/?username=vinitshahdeo&repo=SimpleBio)](https://github.com/vinitshahdeo/SimpleBio) 
 [![HBD](https://github-readme-stats.vercel.app/api/pin/?username=vinitshahdeo&repo=HBD)](https://github.com/vinitshahdeo/HBD)
 [![Map Of India](https://github-readme-stats.vercel.app/api/pin/?username=vinitshahdeo&repo=Map-of-India)](https://github.com/vinitshahdeo/Map-of-India)
 
 
 **Show some ❤️**
    - Consider leaving a ⭐ [here](https://github.com/vinitshahdeo/peerlist-readme-badge/).
    - Check out more beginner-friendly repos [here](https://github.com/vinitshahdeo/Hacktoberfest2021/).
    - Follow @vinitshahdeo for more updates.
    - Read my open-source journey [here](https://www.opensourceforu.com/2020/07/if-you-are-a-techie-your-home-page-should-be-github-not-instagram/).
    - Check my blog: [vinitshahdeo.dev](https://vinitshahdeo.dev/)
 
 #### Say Hi on [Twitter](https://twitter.com/Vinit_Shahdeo)! 👋
 
 [![Twitter Follow](https://img.shields.io/twitter/follow/Vinit_Shahdeo.svg?style=social)](https://twitter.com/Vinit_Shahdeo)
 
 PS: Please add @vinitshahdeo as a reviewer if you haven't added.
 

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: |
 Congrats on merging your first pull request! 🙌🎉⚡️
 Show some love by starring a few of my [repositories](https://github.com/vinitshahdeo?tab=repositories).
